default: true

# Expect dash usage for unordered lists
MD004:
    style: dash

# Allow long line lengths
MD013: false

# Allow duplicate headers for different nesting
MD024:
    allow_different_nesting: true

# Allow Multiple top level headers in the same document
MD025: false

# Ordered lists have all items as 1.
MD029:
    style: one

# Allow inline HTML
MD033: false

# Code block style
MD046:
    style: fenced

# Emphasis in underscore
MD049:
    style: underscore

# Strong in asterisk
MD050:
    style: asterisk

# We check that links are valid ourselves
MD051: false
