repos:
- repo: https://github.com/mattlqx/pre-commit-ruby
  rev: v1.3.5
  hooks:
  - id: rubocop
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint
