name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  RUBY_VERSION: 3.1.3
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  rubocop:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: RuboCop
        run: bin/rubocop

  test-gem-exec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: git-actions/set-user@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          rubygems: latest
          bundler-cache: true
      - name: Wait for release to propagate
        run: gem exec rubygems-await pkg/*.gem
        shell: bash

